name: notizen
services:
  web:
    image: notizen
    container_name: notizen
    ports:
      - '3000:3000'
    volumes:
      - '/volume1/docker/app/data:/app/data'
    environment:
      NOTES_ROOT: /app/data
    restart: always
